site_name: Guidelines for FGP Plugins
nav:
  - Introduction: index.md
  - Guidelines:
      - FGP Author Tool: ./guides/fgpauthor.md
      - Visualize Temporal Data: ./guides/timeseries.md
      - Visualize Complex Data: ./guides/complexdata.md
      - Enable Layer Comparison: ./guides/comparison.md
  - Plugins:
      - Range/Time Slider: ./plugin/rangetimeslider.md
      - Thematic Slider: ./plugin/thematicslider.md
      - Charts: ./plugin/charts.md
      - Swiper: ./plugin/swiper.md
      - Draw ToolBar: ./plugin/draw.md
      - Area of Interest: ./plugin/aoi.md
      - Coordinates Info: ./plugin/coord.md
  - About:
      - Support: about.md

theme:
  name: ivory
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
