site_name: Guidelines for FGP Plugins
nav:
  - User Guidelines: index.md
  - Range/TIme Slider:
      - Overview: rangetimeslider/overview.md
      - Configuration: rangetimeslider/configuration.md
      - Examples: rangetimeslider/use_cases.md
  - Thematic Slider:
      - Overview: thematicslider/overview.md
      - Configuration: thematicslider/configuration.md
      - Examples: thematicslider/use_cases.md
  - About: about.md

theme:
  name: ivory
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
